import type { Metadata } from 'next';
import '@/styles/scss/styles.scss';

export const metadata: Metadata = {
  title: 'My Working Time',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = (props: RootLayoutProps) => {
  return (
    <html lang='en'>
      <body>{props.children}</body>
    </html>
  );
};

export default RootLayout;
